### ISSUE TITLE
Incomplete standard Touchstone Parameter  in option line results in exception

### ISSUE THREAD

**Issue by gzjh1** [mdwhitten/microwave-networks#22]
Example： # Hz S  dB   R 50   
Saved by PNA  
"dB" result in exception

**Comment by mdwhitten** [comment]
Thanks for submitting this! The issue here is that the spec capitalizes both letters for `DB` where the parameter here is `dB`.

I've fixed this in 654b66cb326c88ae5139192a8c8264590ecbf9a0, adding support for case-insensitive header matching and added a unit test to validate. 

Are you able to pull the branch for #24 and validate that the issue is resolved? If not I'll submit trusting the unit test and you can use the updated Nuget package.
